version: '3.9'
services:
  db:
    container_name: db
    image: postgres:13.5-alpine
    env_file: 
      - .env
    ports:
      - 15432:5432
    volumes:
      - ./.data:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 18080:8080
